# Author: lisz1012
# Creation date and time: 12/17/22 8:37 PM

print(bool(False))
print(bool(0))
print(bool(0.0))
print(bool(None))
print(bool(""))
print(bool(''))
print(bool(""""""))
print(bool([]))
print(bool(list()))
print(bool(()))
print(bool(tuple()))
print(bool({}))
print(bool(dict()))
print(bool(set()))
print('--------------')
print(bool(18))
print(bool('hello'))
print(bool(True))